# Q NO1:Develop two 1-D integer array named A and B

In [4]:
import numpy as maliha


In [4]:
A=maliha.random.randint(-7113,7113,size=(7113))
B=maliha.random.randint(-7113,7113,size=(7113))
print(A,B)

[ 2789 -1684  3559 ... -5610 -7111  3523] [5851 1650 -268 ... 5742 6869 -273]


In [5]:
print(A+B)

[8640  -34 3291 ...  132 -242 3250]


In [6]:
print(A-B)

[ -3062  -3334   3827 ... -11352 -13980   3796]


In [9]:
print(A*B)

[ 16318439  -2778600   -953812 ... -32212620 -48845459   -961779]


In [10]:
print(A/B)

[  0.47667065  -1.02060606 -13.27985075 ...  -0.97701149  -1.03523075
 -12.9047619 ]


In [11]:
print(A**3)

[ 219458589 -480614208 2130332919 ... -464821864 1200144233  776143707]


In [12]:
print(max(A))

7108


In [14]:
print(min(B))

-7109


In [15]:
print(maliha.argmin(A))   # MIN VALUE INDEX

4226


In [16]:
print(maliha.argmax(A))    # MIN VALUE INDEX

3100


# Q NO2: 2-D array named A

In [5]:
A= maliha.random.randint(-7113,7113,size=((71,13)))    #71 rows and 13 columns
print(A)

[[-5446  4854 -4200  2524  1513 -1831  6884 -6019 -2224   384 -2678  1931
  -2631]
 [-5762   414  -436  5985 -6310 -4587   555  4709 -5022  6103  6197  2427
  -6377]
 [ 4986  -746 -2877   136  3388  4159   968 -2257  4201  3792  3341 -1803
    -27]
 [-6963 -2836 -2002 -6027 -4668  1040 -6856  6490  5652  -448 -6298 -4624
   1901]
 [-3221  6183 -3066  6997 -4472  5000  1758 -1626 -2538  5076  1196  4664
  -4605]
 [ 3017  -920  5823  5826  3185  5284   490  1030  6017  2610  6428  6706
   -206]
 [  406  1548 -6586   336 -3025  3079   311 -1135 -2083 -4208  3491  6719
   3062]
 [-5371 -2627   486 -2963  2007 -6693 -2113 -6448 -5418 -3489  1129  4729
   6362]
 [  746 -2260  2989   829 -2723 -4576  4920  1545 -4394 -4690 -5001 -2555
   3218]
 [-1470  2309 -1692  1769 -4400 -5446 -6340   503 -3177 -5383  1245 -1117
  -5270]
 [ -878 -5173 -3612  3367  4229  3413  2994  5886  5231 -1795  6456 -4447
  -3407]
 [-4708 -5324 -1627 -3206  1307  1046 -5749  4156  -908   767   595  2969
  -6479]
 [ -

In [5]:
print(A.ndim)

2


In [6]:
print(A[(A>0) &(A%2==0)])

[4854 2524 6884  384  414 4986  136 3388  968 3792 1040 6490 5652 5000
 1758 5076 1196 4664 5826 5284  490 1030 2610 6428 6706  406 1548  336
 3062  486 6362  746 4920 3218 2994 5886 6456 1046 4156 1260 2124 2040
 2150 1798 6402 6090 5512 5386 1428 6760    2  326 2558 6468   96 3860
 2622 6916 4136 4180 4744 4600 2326 6616 3106 1908 6006 6958 1856 3650
 6830 1372 4460 3592 4104 2450 5578 6164 6204 6718  774 4718 1622 4910
  882 2258 3936 2458 2250 1132 4044 2936 2140 3638 1076 6570 5104 1304
 6540 1370 4392 6428 2658 4940 5422 2930 5554 4530 6140 6432 7034 6086
 2826 5480 3280 2288 1772 3608 5666 6302 3860  216 3946  746 1382 4790
 3130 4294 3368 5518 6702 2694 6624  428 5406 7110  718 5460 1822 2346
 5578 6582 6538  740 6718 5988  388 6722 2800 4618 3164 1380 3930 6168
 3652 4550 2802  518  782 6570 6610 3924 1210 4142 4616 1262 5764 1910
 3862 3714 1314 3394 1374 3980  972 2642 2790 4918 6280 2704 1888 4986
  594 5360 4070 3272 3738 2906 5674 1882 6728 4060 2248 3944 5274 3802
 4074 

In [7]:
print(A[(A<0) &(A%2==0)])

[-5446 -4200 -2224 -2678 -5762  -436 -6310 -5022  -746 -2836 -2002 -4668
 -6856  -448 -6298 -4624 -3066 -4472 -1626 -2538  -920  -206 -6586 -4208
 -6448 -5418 -2260 -4576 -4394 -4690 -1470 -1692 -4400 -5446 -6340 -5270
  -878 -3612 -4708 -5324 -3206  -908 -2560  -256 -1620 -4684 -5570 -1356
 -4446 -3640 -6312 -4386 -5498  -644 -2536 -1508 -2452  -100  -234 -1754
 -4240 -2720 -3116 -4656 -4998 -5378 -4808 -3840  -122 -5888  -822 -6158
 -1324 -4830 -6780  -630 -3966 -5098 -2888 -1728 -3136 -3750 -1442 -3022
 -1650 -4072 -6606  -104 -4124 -1934  -424 -5120 -4352  -308 -1430  -906
 -6242 -2796 -4826 -5400  -356   -96  -818 -1170 -1676 -6668 -5908 -5078
 -2386 -6174 -2198 -6916 -2226 -6658 -2552 -6286 -1636 -4236 -5190  -694
 -1588 -5676 -6296 -2556 -3778 -5840 -5128 -3278 -3912 -6448 -1474 -5728
 -1914 -3916 -5370  -882 -6282  -522 -2322 -1132 -5124 -4010 -6094 -6266
 -3566 -4292 -6150 -2120  -754 -3660 -6358 -4764 -4230  -978 -3554 -1302
 -7034 -6088 -4682 -6870 -5680 -6940  -190 -6992 -2

In [8]:
print(A[(A>0) &(A%2!=0)])

[1513 1931 5985  555 4709 6103 6197 2427 4159 4201 3341 1901 6183 6997
 3017 5823 3185 6017 3079  311 3491 6719 2007 1129 4729 2989  829 1545
 2309 1769  503 1245 3367 4229 3413 5231 1307  767  595 2969 5939 6565
 6345 5819 5337  769 5517  421  315 6349 2363  613  695 3951 3493 3119
  571  631 3733 1889 5345 4331 3047 3981 2237 3327 1289 3857 4447  855
 5597 3141 4663 3973 1911 1943 2651 3609 3105 3963 6551 5225 6747 4861
 4229 6647 5889 5857 4685 3727 7097 1711 5073 3989 6417 5815 4531 5215
 3639 5429 1293 2431 4833 4781  287 6351 2945 6373 6545 1135 1923 1685
 4843 3733 3257 6101 1907 3469 3947 5621 6111 4549 6627 3565 3803  203
 2133 4519 7009 6805 1223 5547 6975 4609 2983 2445 5409 2043 3059 6095
 3027 5059 6491 6179 2535 6679  679 4691  355  185 3323 5809 5301 4941
 6721 5485   11 2715 4785 2603 1743 1649 3931 1785 6145 6049 5089 3159
 4215 1667  419 6655  901  671 3169 2535 6379 6991 1225  361 1569 2725
 2253 6403  775 3361 5119 4931 1403 1153 2923 2611 5453 6019 2265 5993
 4805 

In [9]:
print(A[(A<0) &(A%2!=0)])

[-1831 -6019 -2631 -4587 -6377 -2877 -2257 -1803   -27 -6963 -6027 -3221
 -4605 -3025 -1135 -2083 -5371 -2627 -2963 -6693 -2113 -3489 -2723 -5001
 -2555 -3177 -5383 -1117 -5173 -1795 -4447 -3407 -1627 -5749 -6479  -429
 -6531 -4357 -5475 -5821 -1079  -603   -77 -5127 -1707 -6441 -6299 -5429
  -145  -173 -6441  -557 -1821 -4321 -6715 -3237  -719 -2855 -2445 -6767
 -5739 -7051 -3061 -4143 -6849 -3657 -1087 -4507 -3045 -4837 -2805 -5189
 -2627 -5749 -6767 -3631 -3565 -2045 -5483 -4165 -6731 -5897 -2245 -2011
 -4563 -6291 -4177 -5827 -5465 -4647 -3455 -2517 -1433 -1101 -6485 -6783
 -7027 -3877 -1201 -3147 -5335 -3429 -6613 -4095  -597 -5323 -6649 -4867
 -1033 -5251 -5837 -4469 -5951 -5097 -6273 -3437 -7037 -3195 -4455 -3651
  -153 -2047 -4091 -6427 -3999 -2119 -6149  -209 -4667 -5637 -6909 -4581
 -3037 -6035 -3891 -6601  -351 -1619 -6491 -3605 -1617 -6049 -4217 -1283
 -3963 -4949  -919 -2175 -2813 -3879 -6537   -83  -641 -1699 -4423 -7037
 -3487  -373 -5647  -305  -135 -1393 -1857 -2711 -3

In [10]:
print(maliha.sum(A))

151817


In [11]:
print(maliha.sum(A,axis=1))

[ -6939  -2104  17261 -25639  11346  45290   1915 -20409 -11952 -28469
  12264 -17161  29857    562  10811  -9479  23365   7687   6126 -20563
   1089  18616    306   6625   3380 -17743    843  21057 -20057   5713
  18534   4025  23712 -18436   2923 -23544  39170  -3873   7366  -4419
  15254  -8616  -7070   4806 -11447  -7583  15920  -5823    -45  30067
  -2047 -19802  -2426   9597  20443  21475 -14905  -7222 -24609  17365
   6053 -21508    100  13845  14534 -25509  10678  34244   3279  21401
 -17688]


In [12]:
print(maliha.sum(A,axis=0))

[-54308  24986  12781  19742   5348   2330 -28458 -14673  -4278  42483
  19093  53901  72870]


In [13]:
print(A[(A%2==0)|(A%10==0)])

[-5446  4854 -4200  2524  6884 -2224   384 -2678 -5762   414  -436 -6310
 -5022  4986  -746   136  3388   968  3792 -2836 -2002 -4668  1040 -6856
  6490  5652  -448 -6298 -4624 -3066 -4472  5000  1758 -1626 -2538  5076
  1196  4664  -920  5826  5284   490  1030  2610  6428  6706  -206   406
  1548 -6586   336 -4208  3062   486 -6448 -5418  6362   746 -2260 -4576
  4920 -4394 -4690  3218 -1470 -1692 -4400 -5446 -6340 -5270  -878 -3612
  2994  5886  6456 -4708 -5324 -3206  1046  4156  -908  1260  2124 -2560
  2040  2150  1798  -256 -1620  6402 -4684  6090  5512  5386  1428  6760
     2   326 -5570  2558  6468    96 -1356  3860 -4446 -3640  2622  6916
 -6312 -4386  4136  4180  4744  4600 -5498  2326  -644  6616 -2536 -1508
  3106  1908 -2452  6006  -100  6958  -234 -1754 -4240 -2720 -3116  1856
 -4656 -4998 -5378  3650 -4808  6830  1372  4460  3592 -3840  -122  4104
  2450 -5888  5578  6164  -822 -6158  6204 -1324 -4830 -6780  -630  6718
   774  4718  1622 -3966  4910 -5098   882 -2888 -1

In [14]:
print(A[(A%2!=0)&(A>0)&(A%11==0)])

[6017 5819 3047 2651 5225 2431 6545 5621 4609 6721   11 4785 6655  671
  715 5269  187]


In [15]:
print(A[(A%2==0)].size)

468


In [16]:
print(A[(A%2!=0)].size)

455


# QNO3:4-D array named A

In [21]:
A= maliha.random.randint(-7113,7113,size=((((71,13,13,13)))))    #71 block and, 13 group,13 rows,13 column
print(A)

[[[[ 1116  3279 -3284 ...  -596 -2005 -4347]
   [ 6201  2699 -5007 ... -6763 -1513 -4460]
   [ 6766  -330  5486 ... -4387  5490   412]
   ...
   [ 4977 -1975 -6500 ... -7055 -6003   916]
   [-5514 -6342 -5804 ...  3428 -4852 -3847]
   [-1742 -2979  4781 ... -4732 -5586  1344]]

  [[-6945  1437 -6040 ... -4251  -830  2361]
   [-2310  1047  7062 ... -4196   175  3339]
   [-7093 -3905 -2676 ... -3359  2516 -3092]
   ...
   [ -160 -4560 -3163 ...  3459  6833   233]
   [ 5622  5250  1757 ... -2484  6338 -4482]
   [ 1271 -4858  6201 ...  6437  1141  6910]]

  [[ 1030  1492 -3764 ... -1668   123  2207]
   [ 5210  2802  4577 ... -5292 -5102 -5850]
   [-4311 -1036 -2320 ... -6996  -180  3385]
   ...
   [ 2532 -5501  6837 ... -1779  2128  2355]
   [ 1579 -6506  2761 ...   930 -3981  -791]
   [-3101  1478 -1197 ... -5666 -6507 -6144]]

  ...

  [[ 3990  -227 -4341 ...  -846  2906  4507]
   [  435 -2647  2224 ... -6755 -2067 -2181]
   [-3124  6692 -4722 ...  2495 -6617 -3865]
   ...
   [ 2156  282

In [22]:
print(A.ndim)

4


# POSITIVE EVEN

In [23]:
print(A[(A>0)&(A%2==0)])          

[1116 4364 1712 ... 6748 1798 2400]


# DIVISIBLE BY FIRST TWO DIGIT OF AG

In [24]:
print(A[A%71==0])    # ag  7113 

[ 4686  4899  4260 ...  6887 -6106  4047]


# TOTAL NUM OF ZEROS

In [25]:
print(A[A==0].size)

10


# PRINT NEGATIVE VALUES

In [26]:
print(A[A<0])

[-3284 -2466 -4909 ... -6220  -100 -6535]


#  SIZE OF ORIGINAL ARAY

In [27]:
print(A.size)

155987


# NEGATIVE EVEN

In [28]:
print(A[(A<0)&(A%2==0)])

[-3284 -2466  -596 ... -6416 -6220  -100]


# POSITIVE ODD

In [29]:
print(A[(A>0)&(A%2!=0)])

[3279 6653 1295 ... 4789 1365 1809]


# NEGATIVE ODD

In [30]:
print(A[(A<0)&(A%2!=0)])

[-4909 -2005 -4347 ... -2967 -4677 -6535]


#  EVEN AND DIVIDED BY 10

In [31]:
print(A[(A%2==0)|(A%10==0)])

[ 1116 -3284  4364 ... -6416 -6220  -100]


# ODD,EVEN AND DIVIDED BY 11

In [32]:
print(A[(A%2!=0)&(A>0)&(A%11==0)])

[6721 1287  209 ...  231  363  517]


# TOTAL NUM OF POSITIVE EVEN

In [34]:
print(A[(A>0)&(A%2==0)].size)

38872


# TOTAL NUM OF NEGATIVE EVEN

In [35]:
print(A[(A<0)&(A%2==0)].size)

39286


# TOTAL NUM OF EVEN

In [36]:
print(A[(A%2==0)].size)

78168


# TOTAL NUM OF ODD

In [37]:
print(A[(A%2!=0)].size)

77819


#                            THE END